"""init and update user model with int role

Revision ID: 23f2d13d8fed
Revises: 
Create Date: 2026-08-09 06:49:01.080062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '23f2d13d8fed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    connection = op.get_bind()

    # 1. 先把旧的字符串角色映射清洗为纯数字的字符串
    connection.execute(sa.text("UPDATE users SET role = '3' WHERE role = 'lawyer' OR role IS NULL"))
    connection.execute(sa.text("UPDATE users SET role = '1' WHERE role = 'chairman'"))
    connection.execute(sa.text("UPDATE users SET role = '2' WHERE role = 'partner'"))
    connection.execute(sa.text("UPDATE users SET role = '4' WHERE role = 'assistant'"))
    connection.execute(sa.text("UPDATE users SET role = '5' WHERE role = 'admini'"))

    # 2. 核心修复：先删除字段原有的默认值约束，避免类型冲突
    connection.execute(sa.text("ALTER TABLE users ALTER COLUMN role DROP DEFAULT"))

    # 3. 使用 USING 安全地将字段类型转换为 INTEGER
    connection.execute(sa.text("ALTER TABLE users ALTER COLUMN role TYPE INTEGER USING role::integer"))

    # 4. 重新为字段赋予一个新的整型默认值（比如 3 代表普通律师）
    connection.execute(sa.text("ALTER TABLE users ALTER COLUMN role SET DEFAULT 3"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    comment=None,
                    existing_comment='用户角色类型(1-5)',
                    existing_nullable=False,
                    existing_server_default=sa.text("'lawyer'::character varying"))
    # ### end Alembic commands ###
