"""init market table

Revision ID: 82461852434a
Revises: 
Create Date: 2026-08-09 17:40:20.306711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82461852434a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_enterprises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True, comment='地区'),
    sa.Column('enterprise_name', sa.String(length=255), nullable=True, comment='企业名称'),
    sa.Column('legal_representative', sa.String(length=100), nullable=True, comment='法定代表人'),
    sa.Column('contact_info', sa.Text(), nullable=True, comment='联系方式'),
    sa.Column('email', sa.Text(), nullable=True, comment='邮箱'),
    sa.Column('establishment_date', sa.String(length=50), nullable=True, comment='成立日期'),
    sa.Column('registered_capital', sa.Float(), nullable=True, comment='注册资本(万元)'),
    sa.Column('enterprise_type', sa.String(length=100), nullable=True, comment='企业(机构)类型'),
    sa.Column('registered_address', sa.String(length=255), nullable=True, comment='注册地址'),
    sa.Column('enterprise_category', sa.Integer(), nullable=True, comment='企业类别(1-5)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_enterprises_enterprise_category'), 'market_enterprises', ['enterprise_category'], unique=False)
    op.create_index(op.f('ix_market_enterprises_enterprise_name'), 'market_enterprises', ['enterprise_name'], unique=True)
    op.create_index(op.f('ix_market_enterprises_id'), 'market_enterprises', ['id'], unique=False)
    op.create_index(op.f('ix_market_enterprises_region'), 'market_enterprises', ['region'], unique=False)
    op.create_index(op.f('ix_market_enterprises_registered_capital'), 'market_enterprises', ['registered_capital'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_enterprises_registered_capital'), table_name='market_enterprises')
    op.drop_index(op.f('ix_market_enterprises_region'), table_name='market_enterprises')
    op.drop_index(op.f('ix_market_enterprises_id'), table_name='market_enterprises')
    op.drop_index(op.f('ix_market_enterprises_enterprise_name'), table_name='market_enterprises')
    op.drop_index(op.f('ix_market_enterprises_enterprise_category'), table_name='market_enterprises')
    op.drop_table('market_enterprises')
    # ### end Alembic commands ###
